### ISSUE TITLE
v0.67.0 GenerateShares regression

### ISSUE THREAD

**Issue by apreed** [awslabs/aws-service-catalog-puppet#243]
GenerateShares stage of pipeline fails due to error:

AttributeError: 'CreateAssociationsInPythonForPortfolioTask' object has no attribute 'puppet_account_id'

Worked fine in 0.66.0, no changes to manifest since then.

**Comment by apreed** [comment]
I think this line should read self.account_id as puppet_account_id is not available in the Task.

https://github.com/awslabs/aws-service-catalog-puppet/blob/9e46a5f1666a9a57b7940a505522ff991d3cf372/servicecatalog_puppet/workflow/portfoliomanagement.py#L938

**Comment by apreed** [comment]
#244 raised to fix

**Comment by eamonnfaherty** [comment]
resolved in 0.67.1
