### ISSUE TITLE
Dry run is broken

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#119]
Traceback (most recent call last):

File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
new_deps = self._run_get_new_deps()

File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
task_gen = self.task.run()

File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 369, in run
current_version=self.get_current_version(provisioning_artifact_id),

TypeError: get_current_version() missing 1 required positional argument: 'service_catalog'

**Comment by kahilof** [comment]
Hi @eamonnfaherty,

After upgrading to 0.21.0, I'm receiving below error:

Traceback (most recent call last): 
 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps 
    task_gen = self.task.run() 
 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 369, in run 
    current_version=self.get_current_version(provisioning_artifact_id, service_catalog), 
 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 463, in get_current_version 
    ProductId=self.product_id, 
 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
 
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the DescribeProvisioningArtifact operation: Product prod-yewzodli72jn6 does not have specified ProvisioningArtifact pa-oq4xi27kewzqc

**Comment by eamonnfaherty** [comment]
this is fixed now.
